spring:
  application:
    name: authorization
  profiles:
    active: dev

authorization:
  token:
    access-valid-seconds: 3600
    refresh-valid-seconds: 1209600
    use-refresh-token: true

  clients:
    - client-id: my-client
      client-secret: "{noop}my-secret"
      scopes:
        - read
        - write
      grant-types: client_credentials
      jwk:
        jks-path: classpath:keystore/auth.jks
        jks-password: password
        jks-alias: auth-key

    - client-id: another-client
      client-secret: "{noop}another-secret"
      scopes:
        - read
      grant-types: client_credentials
      jwk:
        jks-path: classpath:keystore/auth.jks
        jks-password: password
        jks-alias: auth-key

  url:
    token: /oauth/token
    key: /.well_known/jwks.json